FROM node:18

WORKDIR /app

# Copier uniquement les fichiers de dépendances
COPY ./frontend/package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers
COPY ./frontend /app

# Construire le frontend
RUN npm run build

# Exposer le port
EXPOSE 3000

# Commande de démarrage
CMD ["npm", "start"]

