FROM node:18

WORKDIR /app

# Copier uniquement les fichiers de dépendances
COPY ./back-end/package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers
COPY ./back-end /app

# Exposer le port
EXPOSE 5000

# Commande de démarrage
CMD ["npm", "start"]