# Utilisation d'une image Node.js LTS
FROM node:16

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers de configuration et installer les dépendances
COPY package.json package-lock.json ./
RUN npm install

# Copier le reste du projet
COPY . .

# Exposer le port sur lequel le backend écoute
EXPOSE 4000

# Ajouter pg (si ce n'est pas déjà dans package.json)
RUN npm install pg

# Commande pour démarrer le backend
CMD ["npm", "start"]
