jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Se connecter à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Construire et pousser l'image backend
      - name: Build and push backend
        run: |
          docker build -t your-dockerhub-username/backend:latest -f Dockerfile.backend .
          docker push your-dockerhub-username/backend:latest

      # 4. Construire et pousser l'image frontend
      - name: Build and push frontend
        run: |
          docker build -t your-dockerhub-username/frontend:latest -f Dockerfile.frontend .
          docker push your-dockerhub-username/frontend:latest
